### ISSUE TITLE
change name to just test-models?

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/test-models#17]
following the change of using ss3 as well as @chantelwetzel-noaa 's recent change of the ss-documentation repo to be just doc, perhaps we should rename ss-test-models to test-models?

The only downside is that this repo is a dependency of some test scripts and other things, so we'll need to change it in some other places, also.

**Comment by iantaylor-NOAA** [comment]
I like this idea.

**Comment by Rick-Methot-NOAA** [comment]
concur.  go for it

**Comment by k-doering-NOAA** [comment]
@iantaylor-NOAA , if you could make this change, that would be great! I don't have the permissions. I can then change the names in the github actions workflows that depend on this repo and (if there are any) links to this repo on vlab/github.

**Comment by iantaylor-NOAA** [comment]
Repo is now `test-models`: https://github.com/nmfs-stock-synthesis/test-models.
@k-doering-NOAA, I'll leave this open until you've updated workflows and any links.

**Comment by k-doering-NOAA** [comment]
Thanks @iantaylor-NOAA ! I think I changed the names everywhere in the stock synthesis repos and on vlab, but anyone should feel free to report missed references. Closing.
