### ISSUE TITLE
add model with time varying trend

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/test-models#2]
Thanks to @iantaylor-NOAA for this idea, as it is currently not included in any models in the testing set. Would also be useful for testing r4ss functions in  addition to Stock Synthesis.

**Comment by k-doering-NOAA** [comment]
I wonder if we should create a new subfolder in this repo for storing versions of simple? We could create a separate job (on github actions) that runs through all the versions of simple with no estimation, which at least would tell us if calcs were changing for different model feature in SS. I expect it would run quite quickly, so it may be a way to expand coverage of SS model features without extending runtime for the estimation runs?

I know @kellijohnson-NOAA has advocated for creating code to modify models rather than storing model files, I'm not sure if this is the way to go if we need reference model output files, too?

Thoughts on this? I probably already have ~30 versions of simple on my computer (and everyone else probably has plenty too), so we wouldn't have to make all of these!

**Comment by Rick-Methot-NOAA** [comment]
I completely agree, and that was part of the concept behind the helper
sheets.

A.  create a template input file with a simple structure
B.  have a repository of options on M, growth, selectivity, spawn_recruit
(eventually)
C.  cut from (B) and paste into (A), do run
D.  iterate

**Comment by k-doering-NOAA** [comment]
running with est and no est with the current main branch of stock synthesis passed, so this can stay closed for now.
