### ISSUE TITLE
add a tag for v3.30.20 model files, releases for .18 and .19

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/test-models#32]
@e-gugliotti-NOAA just wanted to flag that now that the 3.30.20 model files have been updated, I would suggest adding a new release and tag to this repository (the tag should be called v3.30.20, to stick with the convention of [existing tags](https://github.com/nmfs-stock-synthesis/test-models/tags)). Github has some [helpful docs on creating releases](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release). No assets need to be added to the release, in this case.

I also suggest creating a release for existing tags that don't have them (.18 and .19).

Feel free to schedule time to go through this together if needed!

**Comment by e-gugliotti-NOAA** [comment]
@k-doering-NOAA I went ahead and did this [here](https://github.com/nmfs-stock-synthesis/test-models/releases). If you want to look it over to make sure I did it correctly.

**Comment by k-doering-NOAA** [comment]
Looks great, thanks!!!
