### ISSUE TITLE
modify "growth morphs" test model

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nmfs-stock-synthesis/test-models#46]
The "growth morphs" test model really has platoons, not growth patterns, so the name should be changed to something like "platoons". I'm not sure what impact renaming the model will have, but I can just try it and find out what breaks.

Now that issue https://github.com/nmfs-stock-synthesis/stock-synthesis/issues/325 has been resolved, the model could also be changed to estimate the platoon variance ratio.

**Comment by Rick-Methot-NOAA** [comment]
agreed.  but I do not know if the data set is likely to be informative regarding sd_ratio;  give it a try

**Comment by iantaylor-NOAA** [comment]
I renamed the model folder and input files from "growth_morphs" to "platoons" and added the Platoon_SD_Ratio parameter, which was estimated at 0.35. I'm now re-ruhning the `call-run-ss3-with-est` workflow to see if anything is broken. I updated ss_summary.sso so it may not flag the model has having different results even though it does (though differences are pretty small anyway).

**Comment by iantaylor-NOAA** [comment]
`call-run-ss3-with-est` seemed to work fine with the renamed model and update reference files, so I'm closing this issue.
